"use client";

import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, Lightbulb, Activity, Coffee, CheckCircle2, XOctagon, Info } from "lucide-react";

export default function InsightsPage() {
  const { data: session } = useSession();
  const [records, setRecords] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/records")
      .then((r) => r.json())
      .then((data) => {
        setRecords(data.records || []);
      })
      .catch((e) => console.error(e))
      .finally(() => setLoading(false));
  }, []);

  if (!session) return null;

  const allDiagnoses = records
    .filter((r) => r.type === "DIAGNOSIS")
    .map((r) => r.title.toLowerCase() + " " + (r.content?.toLowerCase() || ""));

  const hasHypertension = allDiagnoses.some((d) => d.includes("blood pressure") || d.includes("hypertension"));
  const hasDiabetes = allDiagnoses.some((d) => d.includes("diabetes") || d.includes("sugar"));
  const hasFatigue = allDiagnoses.some((d) => d.includes("fatigue") || d.includes("stress"));
  
  const noInsights = !hasHypertension && !hasDiabetes && !hasFatigue;

  return (
    <div className="space-y-10">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white flex items-center gap-3">
          <Lightbulb className="h-8 w-8 text-yellow-500 fill-yellow-500/20" /> 
          Health Insights
        </h1>
        <p className="text-slate-500 dark:text-slate-400 mt-2 max-w-2xl text-lg">
          Automated recommendations generated by analyzing your recent medical records.
        </p>
      </div>

      {loading ? (
        <div className="flex justify-center p-20">
          <Loader2 className="h-10 w-10 animate-spin text-blue-600" />
        </div>
      ) : (
        <div className="grid md:grid-cols-2 gap-8">
          
          <Card className="border-0 shadow-xl dark:bg-slate-900 overflow-hidden group">
            <div className="h-2 bg-emerald-500" />
            <CardHeader className="pb-4 border-b border-slate-100 dark:border-slate-800 flex flex-row items-center gap-3 p-6 bg-emerald-50/30 dark:bg-emerald-900/10">
              <CheckCircle2 className="h-7 w-7 text-emerald-600 dark:text-emerald-400 transition-transform group-hover:scale-110" />
              <CardTitle className="text-2xl font-bold dark:text-white">Recommendations</CardTitle>
            </CardHeader>
            <CardContent className="pt-6 space-y-6 text-slate-700 dark:text-slate-300 p-6">
               {hasHypertension && (
                 <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
                    <Activity className="h-6 w-6 text-emerald-500 flex-shrink-0 mt-0.5" />
                    <div className="space-y-1">
                      <p className="font-bold text-slate-900 dark:text-white">Cardiovascular Health</p>
                      <p className="text-sm leading-relaxed">Aim for 30 minutes of moderate aerobic exercise (brisk walking, swimming) daily to help maintain healthy blood pressure levels.</p>
                    </div>
                 </div>
               )}
               {hasDiabetes && (
                 <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
                    <Activity className="h-6 w-6 text-emerald-500 flex-shrink-0 mt-0.5" />
                    <div className="space-y-1">
                      <p className="font-bold text-slate-900 dark:text-white">Glucose Management</p>
                      <p className="text-sm leading-relaxed">Test your blood sugar levels as scheduled and prioritize a high-fiber, low-glycemic diet.</p>
                    </div>
                 </div>
               )}
               {hasFatigue && (
                 <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
                    <Coffee className="h-6 w-6 text-emerald-500 flex-shrink-0 mt-0.5" />
                    <div className="space-y-1">
                      <p className="font-bold text-slate-900 dark:text-white">Sleep Hygiene</p>
                      <p className="text-sm leading-relaxed">Maintain a consistent sleep-wake schedule and ensure your room is dark and cool for 7-9 hours of rest.</p>
                    </div>
                 </div>
               )}
               {noInsights && (
                 <div className="text-center py-12 px-4">
                   <Info className="h-12 w-12 text-slate-200 dark:text-slate-700 mx-auto mb-4" />
                   <p className="text-slate-500 dark:text-slate-500 italic">No specific action items based on current diagnoses. Keep up your healthy routines!</p>
                 </div>
               )}
            </CardContent>
          </Card>

          <Card className="border-0 shadow-xl dark:bg-slate-900 overflow-hidden group">
            <div className="h-2 bg-red-500" />
            <CardHeader className="pb-4 border-b border-slate-100 dark:border-slate-800 flex flex-row items-center gap-3 p-6 bg-red-50/30 dark:bg-red-900/10">
              <XOctagon className="h-7 w-7 text-red-600 dark:text-red-400 transition-transform group-hover:scale-110" />
              <CardTitle className="text-2xl font-bold dark:text-white">Precautions</CardTitle>
            </CardHeader>
            <CardContent className="pt-6 space-y-6 text-slate-700 dark:text-slate-300 p-6">
               {hasHypertension && (
                 <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
                    <span className="text-red-500 text-2xl leading-none mt-1 select-none">•</span>
                    <div className="space-y-1">
                      <p className="font-bold text-slate-900 dark:text-white">Sodium Intake</p>
                      <p className="text-sm leading-relaxed">Strictly limit salt (sodium) intake. Avoid canned soups, processed meats, and high-sodium frozen meals.</p>
                    </div>
                 </div>
               )}
               {hasDiabetes && (
                 <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
                    <span className="text-red-500 text-2xl leading-none mt-1 select-none">•</span>
                    <div className="space-y-1">
                      <p className="font-bold text-slate-900 dark:text-white">Refined Sugars</p>
                      <p className="text-sm leading-relaxed">Avoid sugary beverages, refined white carbohydrates, and desserts that cause rapid glucose spikes.</p>
                    </div>
                 </div>
               )}
               {hasFatigue && (
                 <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
                    <span className="text-red-500 text-2xl leading-none mt-1 select-none">•</span>
                    <div className="space-y-1">
                      <p className="font-bold text-slate-900 dark:text-white">Late Stimulants</p>
                      <p className="text-sm leading-relaxed">Avoid caffeine and energy drinks after 2 PM to ensure they don't interfere with your body's natural sleep cycle.</p>
                    </div>
                 </div>
               )}
               {noInsights && (
                 <div className="text-center py-12 px-4">
                    <Info className="h-12 w-12 text-slate-200 dark:text-slate-700 mx-auto mb-4" />
                    <p className="text-slate-500 dark:text-slate-500 italic">No specific dietary or lifestyle restrictions indicated by your current records.</p>
                 </div>
               )}
            </CardContent>
          </Card>

        </div>
      )}
      
      <div className="bg-blue-50 dark:bg-blue-900/10 border border-blue-100 dark:border-blue-800 p-6 rounded-3xl mt-8">
        <h3 className="font-bold text-blue-900 dark:text-blue-300 mb-2 flex items-center gap-2">
          <Info className="h-4 w-4" /> Note on Automated Insights
        </h3>
        <p className="text-blue-800/80 dark:text-blue-400/80 text-sm leading-relaxed">
          These recommendations are generated based on identified patterns in your clinical history. They complement but do not replace your doctor&apos;s personalized medical advice. Always consult your healthcare provider before making significant lifestyle changes.
        </p>
      </div>
    </div>
  );
}
