import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY || "");

const SYSTEM_PROMPT = `
You are the SympTax Clinical AI Agent. You are specialized in providing health analysis, wellness information, and identifying clinical patterns.

STRICT GUARDRAILS:
1. ONLY discuss health, wellness, medicine, symptoms, and medical sciences.
2. If a user asks about non-medical topics (e.g., politics, coding, general chat), politely state that you are a specialized medical assistant and redirect them to health-related queries.
3. NEVER provide a definitive medical diagnosis.
4. ALWAYS include a disclaimer in your response.
5. Provide structured, empathetic, and professional advice.
6. Use clear headings: ANALYSIS, REASONING, and STRATEGIC RECOMMENDATIONS.
`;

export async function POST(req: Request) {
  try {
    const { message, history } = await req.json();

    if (!message) {
      return NextResponse.json({ message: "Message is required" }, { status: 400 });
    }

    if (!process.env.GOOGLE_AI_API_KEY) {
      return NextResponse.json({ 
        response: "SympTax AI Warning: Google Gemini API Key is missing. Please configure it in the environment variables." 
      }, { status: 200 }); 
    }

    const model = genAI.getGenerativeModel({ 
      model: "gemini-1.5-flash",
      systemInstruction: SYSTEM_PROMPT
    });

    const formattedHistory = (history || []).map((msg: any) => ({
      role: msg.role === "bot" ? "model" : "user",
      parts: [{ text: msg.content }],
    }));

    const chat = model.startChat({
      history: formattedHistory,
    });

    const result = await chat.sendMessage(message);
    const responseText = result.response.text();

    const formattedResponse = `
${responseText}

---
**SYMPTAX DISPATCH:** This analysis was generated by a clinical AI agent. It is for informational purposes and **NOT a medical diagnosis**. Please consult your doctor for clinical decisions.
    `.trim();

    return NextResponse.json({ response: formattedResponse }, { status: 200 });
  } catch (error: any) {
    console.error("GEMINI_ERROR:", error);
    return NextResponse.json({ message: "Health Agent Error: The AI knowledge base is currently unavailable." }, { status: 500 });
  }
}
